# async/await in Swift

Swift에서 비동기 처리를 하는 방법은 Completion handler를 이용하거나 Swift 5.5 이후부터 async/await 키워드를 이용하여 함수의 호출이 끝나는 시점을 알 수 있다. 기존에 시간이 오래걸리는 비동기 작업을 처리시 completion handler를 이용하여 주로 처리하였지만 async/await를 이용해보고 싶어서 WWDC를 찾아보면서 추가적으로 공부한 내용을 정리하게 되었다.

### 비동기 처리가 필요한 이유부터

비동기 처리가 필요한 가장큰 이뉴는 시간이 오래걸리는 작업들을 기다리지 않고 처리를 하기위해서이다. 네트워크 요청으로 사진과 영상을 받아오는 작업의 경우 시간이 오래걸리는 작업일 수 있다. 그렇다면 왜? 이러한 작업들이 문제가 되는것일까?



운영체제 내부에서는 run loop라는 객체에서 1초에 60번정도 화면을 다시 렌더하는 작업을 수행한다. 물론 스크롤을 한다던지 화면의 데이터가 변경되어 UI의 변경이 필요할때 이러한 과정을 거치게된다. 또한 이러한 과정은 메인스레드에서 일어난다. 메인스레드에서는 이러한 화면을 그리는 작업이 진행하기 때문에 만약 메인스레드에서 시간이 오래걸리는 작업을 수행한다고 가정하면 화면이 버벅이거나 앱이 부자연스러워 보이는 현상이 일어날 수 있다. 이러한 이유들 때문에 시간이 오래걸리는 작업은 다른 스레드로 위임하고 작업이 완료되었을때 결과를 받아야한다.

<img src = "https://github.com/Seokki-Kwon/Seokki-Kwon/assets/101062450/84923e55-3fa8-458f-9c10-c3f9383968be"/>

맞는 그림이 없어서 직접 pages로 제작했다 비동기 컨텍스트에서 실행되는 이러한 작업들은 메인스레드가 아닌 다른 스레드로 작업을 던지고 Long Task에서 작업이 완료가 되었을때 결과를 전달받는다. 다른 스레드에서 작업을 수행하도록 하는방법은 Grand Central Dispatch를 이용한다.

```swift
DispatchQueue.global().async {
    // 비동기 작업
}
```

다시 결론으로 돌아와서 평소에 내가 사용하던 방식인 completion handler를 이용하는 방식은 작업의 완료시점을 알기위해서 @escaping 키워드를 이용한 탈출클로저를 구현하여 비동기 결과를 받아와서 사용하던것이다.

```swift
func someNetorkTask(withUrl: String, completion: @escaping (Result<Bool, NetworkError>) -> ())  {
    let session: URLSession = URLSession(configuration: .default)
    
    session.dataTask(with: URLRequest(url: URL(string: withUrl)!)) { data, response, error in
        if let error = error {
            completion(.failure(NetworkError.someError))
        } else {
            completion(.success(true))
        }
    }
    .resume()
}


someNetorkTask(withUrl: "https://www.naver.com") { result in
    switch result {
    case .success(_):
        print("성공!")
    case .failure(let error):
        print(error.localizedDescription)
    }
}
```
물론 현재 방식이 편해져서 프로젝트를 할때에도 해당 방식을 했지만 처음에 보기애는 조금 이해가 쉽지안을 뿐더러 한개의 요청만으로 작업이 끝나지 않는 경우가 있을 수 있다.

```swift
someNetorkTask(withUrl: "https://www.naver.com") { result in
    someNetworkTask2(networkTaskRespone: result) { result2 in
        someNetworkTask3(networkTask2Respone: result2) { result3 in
            finalTask(result3)
        }
    }
}
```
또한 someNetworkTask에서 에러처리 같은 작업을 하다가 completion handler를 호출하지 않는 상황이 생길 수 있다는 문제가 발생하고 적절한 곳에 completion handler를 직접 배치시키는것도 생각보다 귀찮은 작업이다. 
```swift
func someNetorkTask(withUrl: String, completion: @escaping (Result<Bool, NetworkError>) -> ())  {
    let session: URLSession = URLSession(configuration: .default)
    
    session.dataTask(with: URLRequest(url: URL(string: withUrl)!)) { data, response, error in
        if let error = error {
            completion(.failure(NetworkError.someError))
        } else {
            // 까먹고 호출해도 정상실행
        }
    }
    .resume()
}
```

처음에는 이러한 상황을 마주해보지 않는다면 와닿지 않을 수 있지만 실제 최종프로젝트를 했을떄 정말 완료핸들러가 2중3중 4중까지 쌓이는 일을 경험했다... 이렇게 클로저가 2중3중 겹겹히 쌓이는 일들을 콜백지옥 또는 클로저지옥 이라고한다. 이러한 콜백지옥을 async/await를 이용하여 해결할 수 있다.

```swift
func someNetorkTask(withUrl: String) async throws -> String? {
    let session: URLSession = URLSession(configuration: .default)
    let request = URLRequest(url: URL(string: withUrl)!)
    
    do {
        let (data, response) = try await session.data(for: request)
        return "SomeString"
    } catch {
        throw NetworkError.someError
    }
}
```
async/await를 이용하도록 함수를 다시 설계해야한다. URLSession도 사용법이 기존과 다르게 async/await를 이용한 함수의 구현으로 변경했다. 여기서 await의 의미는 현재 스레드의 제어권을 포기하고 System에게 제어권을 넘긴다는 의미로 컴파일러가 받아들이고 수행한다.

<img src = "https://github.com/Seokki-Kwon/Seokki-Kwon/assets/101062450/9afaaf69-b1d3-4106-a485-598f0cbfecef"/> <br/>
동기함수의 경우 함수가 실행이 되면 스택프레임에서 함수가 실행이 되면서 해당 실행되는 함수가 스레드의 제어권을 쥐고 작업을 수행한다. 그상태에서 또다른 함수를 호출하는 경우 호출된 함수에게 스레드의 제어권이 넘어가게된다. 이게 일반적인 동기함수의 실행 과정이다. <br/>

fetchTumbnail(control) -> thumbnailURLRequest -> fetchThumbnail <br/> 
fetchTumbnail -> thumbnailURLRequest(control) -> fetchThumbnail  <br/>
fetchTumbnail -> thumbnailURLRequest -> fetchThumbnail(control)  <br/>

<img src = "https://github.com/Seokki-Kwon/Seokki-Kwon/assets/101062450/367aa715-a98e-46e8-97b8-20460b3cfb51" />

await를 이용한 비동기처리를 하는경우 await문을 만나는 경우 해당 현재의 함수는 Suspend 상태가 된다 해당 함수가 Suspend가 되면서 제어권은 System에게 위임되며 System은 자체적인 판단으로 스레드를 할당하여 작업을 수행하며 작업이 완료되면 재개(resume) 하여 함수의 제어권을 다시 반환하게 된다.

그렇다면 이렇게 작성된 비동기 함수를 실제로 뷰컨이나 뷰에서 사용하기 위해서는 어떻게 해야할까? 현재 async로 작성된 함수의 경우 일반적인 환경에서 호출될 수 없는 함수이다.

```swift
struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world!")
        }
        .padding()
        .onAppear {
            someAsyncFunc()
        }
    }
}
```
비동기함수를 onAppear에서 호출하려고하면 'async' call in a function that does not support concurrency 라는 에러가 발생한다. 비동기 컨텍스트가 아닌 곳에서 함수를 호출하려고 했기때문이다 이럴때는 Task 구조체를 이용하여 비동기 함수를 호출해야한다.

```swift
struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world!")
        }
        .padding()
        .onAppear {
            Task {
                await someAsyncFunc()
            }
        }
    }
}
```

## 참고링크
- [[WWDC]Meet async/await in Swift](https://developer.apple.com/videos/play/wwdc2021/10132/)
